dist: trusty
sudo: required
language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential mercurial cmake libzip-dev libxaw7-dev libfreeimage-dev libfreetype6-dev git libtinyxml-dev libzzip-dev libois-dev

before_script:
  - goback=$(pwd)
  - cd /tmp
  - mkdir prefix
  - cd prefix
  - wget http://ybalrid.info/files/ogre21.tar.xz
  - tar xvJf ogre21.tar.xz
  - rm ogre21.tar.xz
  - sudo cp -r * /
  - sudo ldconfig -v
  - cd $goback
  
script:
  - cd build
  - cmake ..
  - make
  
  
